//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "questions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub text: String,
    pub answers: i32,
    pub correct_answer: i32,
    pub deleted: Option<i8>,
    pub created: Option<Date>,
    pub test_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::answer::Entity",
        from = "Column::CorrectAnswer",
        to = "super::answer::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Answers,
    #[sea_orm(
        belongs_to = "super::test::Entity",
        from = "Column::TestId",
        to = "super::test::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Tests,
}

impl Related<super::answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Answers.def()
    }
}

impl Related<super::test::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
